# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_grabar_boton(object):
    def setupUi(self, grabar_boton):
        grabar_boton.setObjectName("grabar_boton")
        grabar_boton.resize(884, 554)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        grabar_boton.setFont(font)
        grabar_boton.setStyleSheet("")
        self.Grabar = QtWidgets.QPushButton(grabar_boton)
        self.Grabar.setGeometry(QtCore.QRect(30, 410, 91, 21))
        self.Grabar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Grabar.setObjectName("Grabar")
        self.controlador_metronomo = QtWidgets.QDial(grabar_boton)
        self.controlador_metronomo.setGeometry(QtCore.QRect(210, 410, 91, 71))
        self.controlador_metronomo.setMouseTracking(False)
        self.controlador_metronomo.setObjectName("controlador_metronomo")
        self.listView = QtWidgets.QListView(grabar_boton)
        self.listView.setGeometry(QtCore.QRect(20, 141, 311, 181))
        self.listView.setObjectName("listView")
        self.parar_boton = QtWidgets.QPushButton(grabar_boton)
        self.parar_boton.setGeometry(QtCore.QRect(30, 510, 90, 21))
        self.parar_boton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.parar_boton.setMouseTracking(False)
        self.parar_boton.setObjectName("parar_boton")
        self.eliminar_boton = QtWidgets.QPushButton(grabar_boton)
        self.eliminar_boton.setGeometry(QtCore.QRect(240, 340, 90, 21))
        self.eliminar_boton.setObjectName("eliminar_boton")
        self.progressBar = QtWidgets.QProgressBar(grabar_boton)
        self.progressBar.setGeometry(QtCore.QRect(540, 500, 281, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(grabar_boton)
        self.lcdNumber_2.setGeometry(QtCore.QRect(40, 440, 71, 51))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label = QtWidgets.QLabel(grabar_boton)
        self.label.setGeometry(QtCore.QRect(10, -20, 91, 161))
        self.label.setStyleSheet("border-image: url(:/dolp/d_textura.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(grabar_boton)
        self.label_2.setGeometry(QtCore.QRect(100, 10, 191, 81))
        font = QtGui.QFont()
        font.setFamily("C059 [UKWN]")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(113, 113, 113);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(grabar_boton)
        self.label_3.setGeometry(QtCore.QRect(100, 60, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(116, 116, 116);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(grabar_boton)
        self.label_4.setGeometry(QtCore.QRect(130, 410, 21, 21))
        self.label_4.setStyleSheet("border-image: url(imagenes/tocar.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(grabar_boton)
        self.label_5.setGeometry(QtCore.QRect(130, 510, 21, 21))
        self.label_5.setStyleSheet("border-image: url(imagenes/detener.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(grabar_boton)
        self.label_6.setGeometry(QtCore.QRect(210, 340, 21, 21))
        self.label_6.setStyleSheet("border-image: url(imagenes/compartimiento.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(grabar_boton)
        self.pushButton.setGeometry(QtCore.QRect(70, 340, 90, 21))
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtWidgets.QLabel(grabar_boton)
        self.label_8.setGeometry(QtCore.QRect(30, 340, 31, 16))
        self.label_8.setStyleSheet("border-image: url(imagenes/ondas-de-audio.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(grabar_boton)
        self.label_9.setGeometry(QtCore.QRect(210, 480, 91, 16))
        self.label_9.setObjectName("label_9")
        self.frame = QtWidgets.QFrame(grabar_boton)
        self.frame.setGeometry(QtCore.QRect(410, 150, 431, 171))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 391, 151))
        self.label_7.setStyleSheet("border-image: url(imagenes/ondas.jpg);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(grabar_boton)
        self.label_10.setGeometry(QtCore.QRect(410, 120, 281, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(grabar_boton)
        self.label_11.setGeometry(QtCore.QRect(20, 120, 131, 16))
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(grabar_boton)
        self.label_13.setGeometry(QtCore.QRect(830, 20, 31, 31))
        self.label_13.setStyleSheet("border-image: url(imagenes/ayuda.png);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.instrucciones = QtWidgets.QPushButton(grabar_boton)
        self.instrucciones.setGeometry(QtCore.QRect(730, 30, 91, 21))
        self.instrucciones.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.instrucciones.setObjectName("instrucciones")
        self.pushButton_2 = QtWidgets.QPushButton(grabar_boton)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 450, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(grabar_boton)
        QtCore.QMetaObject.connectSlotsByName(grabar_boton)

    def retranslateUi(self, grabar_boton):
        _translate = QtCore.QCoreApplication.translate
        grabar_boton.setWindowTitle(_translate("grabar_boton", "Dialog"))
        self.Grabar.setText(_translate("grabar_boton", "Grabar"))
        self.parar_boton.setText(_translate("grabar_boton", "Parar"))
        self.eliminar_boton.setText(_translate("grabar_boton", "Eliminar"))
        self.label_2.setText(_translate("grabar_boton", "DOLPHings"))
        self.label_3.setText(_translate("grabar_boton", "Tabs"))
        self.pushButton.setText(_translate("grabar_boton", "Reproducir"))
        self.label_9.setText(_translate("grabar_boton", "Metronomo"))
        self.label_10.setText(_translate("grabar_boton", "Frecuencias Detectadas por microfono:"))
        self.label_11.setText(_translate("grabar_boton", "Lista de Grabaciones:"))
        self.instrucciones.setText(_translate("grabar_boton", "Instrucciones"))
        self.pushButton_2.setText(_translate("grabar_boton", "Generar Tab"))

from imagenes import *


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    grabar_boton = QtWidgets.QDialog()
    ui = Ui_grabar_boton()
    ui.setupUi(grabar_boton)
    grabar_boton.show()
    sys.exit(app.exec_())
